version: '3'

services:
  openproject:
    image: openproject/community:latest
    restart: always
    volumes:
      - /opt/openproject/pgdata:/var/lib/postgresql/9.6/main
      - /opt/openproject/logs:/var/log/supervisor
      - /opt/openproject/static:/var/db/openproject
    expose:
      - 80
    environment:
      - SECRET_KEY_BASE=secret
  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443